institute :
  name : ICET


spring :
  datasource :
    url : jdbc:mysql://localhost:3306/studentManagementSystem
    username : root
    password : 1234
  jpa :
    hibernate :
      ddl-auto : update
